### ISSUE TITLE
Authentication against AWS is attempted even when session.handler_id is not set to dynamo_session_handler

### ISSUE THREAD

**Issue by choonge** [gwkunze/dynamo-session-bundle#1]
I want to use DynamoDB for session handling only on staging and production, not on my local dev environment. To achieve this, I have this in my config.yml:

``` yml
framework:
    session:
        handler_id: %session.handler_id%

gwk_dynamo_session:
    aws:
        key: %session.dynamo_aws_key%
        secret: %session.dynamo_aws_secret%
```

And in my parameters.yml.dist:

``` yml
parameters:
    session.handler_id: null
    session.dynamo_aws_key: null
    session.dynamo_aws_secret: null
```

After a `composer install` on my local dev environment, I press 3x [enter] for these parameters since I don't intend to use DynamoDB. That means the above null values are copied to my actual parameters.yml.

When I then hit the frontend, I get this error:

```
LogicException: Invalid DynamoDB security credentials or insufficient permissions
```

Expected behaviour: if session.handler_id is null, it defaults to the session handler configured in php.ini. At this point, no authentication against AWS should be attempted.

Will send a pull request.
